# Generated by Django 3.0.7 on 2020-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
