# Generated by Django 3.0.7 on 2020-06-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200612_1916'),
        ('blog', '0010_auto_20200612_2020'),
    ]

    operations = [
    ]
