# Generated by Django 3.0.7 on 2020-06-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_20200612_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentitem', to='blog.Blog'),
        ),
    ]
